<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>management_tab</name>
   <tag></tag>
   <elementGuidId>e715b452-65ea-40c5-a0ae-0579fc15f126</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#managementDropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='managementDropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7a47c2c9-900a-41cc-bc8c-a360cdafb30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/management</value>
      <webElementGuid>a2cf9a8d-74e7-4b29-98a7-3ed70ac8321f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>managementDropdown</value>
      <webElementGuid>a0d4d148-a45a-4571-aaf9-511ae160b20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>a995d231-2e34-4462-a9e4-df4545d96459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-dismiss</name>
      <type>Main</type>
      <value>offcanvas</value>
      <webElementGuid>df30b3b7-113b-4821-82fc-6d3a21ccdf0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>.navbar-collapse.show</value>
      <webElementGuid>aae5ce7e-c3fc-48e4-a880-761fc0bcc48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item dropdown-toggle</value>
      <webElementGuid>0391fa30-780a-4290-8a76-2bc63024f5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Management</value>
      <webElementGuid>753d31c7-d785-4934-93a9-c6b04432ebf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;managementDropdown&quot;)</value>
      <webElementGuid>90bd3d6a-fe09-4883-968f-a1f240c70e11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='managementDropdown']</value>
      <webElementGuid>ea8d7991-964d-4533-a395-451a33d58e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='offcanvasNavbar']/div[2]/ul/li/ul/li[3]/div/a</value>
      <webElementGuid>51b72331-1bf5-4a9b-9430-529243115a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Management')]</value>
      <webElementGuid>b6e0723f-3551-4bc8-bf49-cc2b35ec76bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Content'])[2]/following::a[1]</value>
      <webElementGuid>4a979fb6-fcdb-472f-a512-8fd0a311e719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Messages'])[2]/following::a[2]</value>
      <webElementGuid>51119063-4f6a-4d0f-a0f3-71f843c0b3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounts'])[1]/preceding::a[1]</value>
      <webElementGuid>94eca27c-645f-4fef-857d-5cd94b8c8065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clients'])[1]/preceding::a[2]</value>
      <webElementGuid>2612fadb-27a3-404f-b2dd-8c47c9bfff0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Management']/parent::*</value>
      <webElementGuid>08a17f58-1999-4c4f-9454-4f0d8f8a8189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/management')]</value>
      <webElementGuid>20d78e03-3f60-4e85-a227-d68bfd0a4b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/a</value>
      <webElementGuid>d19f6a78-cd6c-4fea-bfe5-be41397ece6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/management' and @id = 'managementDropdown' and (text() = 'Management' or . = 'Management')]</value>
      <webElementGuid>9aba56b8-ee41-45dd-a067-27d2e66516f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
