<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vendors_tab</name>
   <tag></tag>
   <elementGuidId>319225a1-c9f6-4db9-a622-9dc547ea507a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vendorDropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='vendorDropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81077b4b-9ac4-4099-9f11-8fca8be43dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/management/vendors</value>
      <webElementGuid>1da01a2d-307c-4eca-a4d2-d25227ac282e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vendorDropdown</value>
      <webElementGuid>d743d370-afa7-4839-ab40-fbfb7e641b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>f131d34d-fa0c-4403-be9a-a63a52c94603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-dismiss</name>
      <type>Main</type>
      <value>offcanvas</value>
      <webElementGuid>3e74437b-4926-407f-886c-2138bafd4d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>.navbar-collapse.show</value>
      <webElementGuid>ebe0006e-07f7-4b33-a78f-4269a9f2baf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item dropdown-toggle</value>
      <webElementGuid>8c27c9e9-7907-4676-a62a-7e8a365ac410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vendors</value>
      <webElementGuid>575b7c8c-6bed-479d-9610-47d6f1bb1534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vendorDropdown&quot;)</value>
      <webElementGuid>ab5431d2-8777-460f-8b7e-1d7bcc3c78d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='vendorDropdown']</value>
      <webElementGuid>51bee4a0-52b5-4bf4-b222-fe15e61ce08c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='offcanvasNavbar']/div[2]/ul/li/ul/li[3]/div/div/li[14]/div/a</value>
      <webElementGuid>fd01b020-b7a3-41ca-9be4-fce249959728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Vendors')]</value>
      <webElementGuid>b0a9740a-8232-4a2e-9a1a-55c22169f5db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FBOs'])[1]/following::a[1]</value>
      <webElementGuid>6c16ec8c-06a6-4599-8a28-c86f84d92040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operator Aircraft Rates'])[1]/following::a[2]</value>
      <webElementGuid>1b3502e2-c5c8-41de-9b64-53c2215de6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Locations'])[1]/preceding::a[1]</value>
      <webElementGuid>08035c91-4f40-4194-8fe9-b0cc50a91d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilots'])[1]/preceding::a[2]</value>
      <webElementGuid>f7b3a0cb-5217-4389-8e46-a1354194a792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vendors']/parent::*</value>
      <webElementGuid>e5385128-957c-45ef-a717-951a210a9150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/management/vendors')]</value>
      <webElementGuid>f1c348bd-6f4e-449d-b38b-29896f7b65aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[14]/div/a</value>
      <webElementGuid>fc9097c4-a6cc-4fa2-8f97-126afb01bae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/management/vendors' and @id = 'vendorDropdown' and (text() = 'Vendors' or . = 'Vendors')]</value>
      <webElementGuid>d8c8ebf6-a295-4f62-af91-293aa4e819ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
